# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -vv"
testpaths = [
    "tests",
    "integration",
]
markers = [
    "tests",
    "integration",
    "high",
    "medium",
    "low",
]
[tool.flake8]
exclude = [".build"]

[tool.black]
target-version = ['py38']
exclude = '''
/(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | _build
    | build
    | dist
    | migrations
)/
'''

[tool.isort]
profile = "black"
src_paths = ["dundie", "tests", "integration"]
multi_line_output = 3